# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh("flutter", "build", "appbundle", "--release", "--flavor", "mobile", "--dart-define=edu.rit.csh.devin.flavor=mobile")
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/mobileRelease/app-mobile-release.aab",
      skip_upload_changelogs: true
    )
    #sh("flutter", "build", "appbundle", "--release", "--flavor", "wearos", "--dart-define=edu.rit.csh.devin.flavor=wearos")
    upload_to_play_store(
      track: "wear:internal",
      aab: "../build/app/outputs/bundle/wearosRelease/app-wearos-release.aab",
      skip_upload_changelogs: true
    )
  end
end
